version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: